Adds Next button to progress through work form tabs
sul-dlss/hungry-hungry-hippo pull request #153
Opened 2024-11-21 20:32 UTC by lwrubel

Closes #111 to add a next button to panes (except for the last pane).

![Screenshot 2024-11-21 at 3 25 58 PM](https://github.com/user-attachments/assets/63ecd333-dd16-4fbf-b992-dd30385776ee)

2024-11-21 20:54 UTC, justinlittman requested changes

2024-11-21 20:54 UTC, justinlittman commented on app/javascript/controllers/tab_next_controller.js
> +    const tabsOrder = ["title", "abstract", "related_content", "deposit"]
I really don't like having this hard-coded in here. It is inevitable that we will changes tabs and forget to update.

2024-11-22 13:07 UTC, lwrubel commented on app/javascript/controllers/tab_next_controller.js
> +    const tabsOrder = ["title", "abstract", "related_content", "deposit"]
Yeah, that was a compromise since the code for the next button is shared, unlike the POC. I thought that the system test, by using the tabs, would catch any missed updates for future tab changes. I'll try to do this another way.

2024-11-22 21:07 UTC, lwrubel commented on app/javascript/controllers/tab_next_controller.js
> +    const tabsOrder = ["title", "abstract", "related_content", "deposit"]
next tab selection is now a param in each pane

2024-11-25 13:44 UTC, lwrubel commented on app/components/elements/button_component.rb
> +module Elements
Added a spec

2024-11-25 18:30 UTC, merged